[package]
name = "profile"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["json"]}
rocket_cors = "0.6.0"
diesel = { version = "2.2.0", features = ["postgres"] }
